plugins {
    id 'java'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/Vontk/ingsis-interpreter")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("USERNAME") ?: System.getenv("GITHUB_ACTOR")
            password = project.findProperty("gpr.key") ?: System.getenv("TOKEN") ?: System.getenv("GITHUB_TOKEN")
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

test {
    minHeapSize = "5m" // initial heap size
    maxHeapSize = "5m" // maximum heap size
}

dependencies {
    def printscriptVersion = '0.2.0-ci.1.f1b702d47899'
    implementation "org.printscript:runner:${printscriptVersion}"
    implementation "org.printscript:runtime-api:${printscriptVersion}"
    implementation "org.printscript:common:${printscriptVersion}"
    implementation "org.printscript:configuration:${printscriptVersion}"
    implementation "org.printscript:linter:${printscriptVersion}"
    implementation "org.printscript:formatter:${printscriptVersion}"
    testImplementation 'junit:junit:4.13.1'
}

test {
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"
    useJUnit()
}
