plugins {
    id 'java'
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        name = "GitHubPackages"
        url = uri("https://maven.pkg.github.com/printScript-ingsis-vlt/print-script-ingsis")
        credentials {
            username = project.findProperty("gpr.user") ?: System.getenv("GITHUB_ACTOR")
            password = project.findProperty("gpr.key")  ?: System.getenv("GITHUB_TOKEN")
        }
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.1'
    implementation("com.printscript:common-ast:1.1.0")
    implementation("com.printscript:formatter:1.1.0")
    implementation("com.printscript:cli:1.1.0")
    implementation("com.printscript:common-lexer-parser:1.1.0")
    implementation("com.printscript:common-result:1.1.0")
    implementation("com.printscript:common-runtime:1.1.0")
    implementation("com.printscript:interpreter:1.1.0")
    implementation("com.printscript:lexer:1.1.0")
    implementation("com.printscript:linter:1.1.0")
    implementation("com.printscript:parser:1.1.0")
    implementation("com.printscript:semantic:1.1.0")
}

dependencies {
    testImplementation 'junit:junit:4.13.1'
}

test {
    minHeapSize = "5m"
    maxHeapSize = "7m"
    environment "BEST_FOOTBALL_CLUB", "San Lorenzo"
    useJUnit()
}
